# Generated by Django 4.0 on 2022-01-07 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('SWGOHPk', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GearLevels',
            fields=[
                ('level', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModSets',
            fields=[
                ('SWGOHPk', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModStats',
            fields=[
                ('statID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('divisor', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('allyCode', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('modID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('slot', models.PositiveIntegerField()),
                ('dots', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField()),
                ('primaryStatValue', models.PositiveIntegerField()),
                ('secondaryStat1Value', models.PositiveIntegerField()),
                ('secondaryStat2Value', models.PositiveIntegerField()),
                ('secondaryStat3Value', models.PositiveIntegerField()),
                ('secondaryStat4Value', models.PositiveIntegerField()),
                ('primaryStatType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primaryStatModSet', to='TeamMod.modstats')),
                ('secondaryStat1Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondaryStat1ModSet', to='TeamMod.modstats')),
                ('secondaryStat2Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondaryStat2ModSet', to='TeamMod.modstats')),
                ('secondaryStat3Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondaryStat3ModSet', to='TeamMod.modstats')),
                ('secondaryStat4Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondaryStat4ModSet', to='TeamMod.modstats')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamMod.modsets')),
            ],
        ),
        migrations.CreateModel(
            name='HasActivated_EquippedWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField()),
                ('numOfGear', models.PositiveIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamMod.characters')),
                ('gearLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamMod.gearlevels')),
                ('modSlot1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modSlot1ActivatedSet', to='TeamMod.mods')),
                ('modSlot2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modSlot2ActivatedSet', to='TeamMod.mods')),
                ('modSlot3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modSlot3ActivatedSet', to='TeamMod.mods')),
                ('modSlot4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modSlot4ActivatedSet', to='TeamMod.mods')),
                ('modSlot5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modSlot5ActivatedSet', to='TeamMod.mods')),
                ('modSlot6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modSlot6ActivatedSet', to='TeamMod.mods')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamMod.players')),
            ],
            options={
                'unique_together': {('player', 'character')},
            },
        ),
    ]
